enable-module-update = true
parallel-jobs = 1
rv-brand = "Morphe"
patches-version = "dev"
cli-version = "newest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/elohim-etz/morphe-builder/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
build-mode = "both"
